import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@evolt/components/common/theme-provider";
import "./globals.css";
import { Toaster } from "@evolt/components/ui/sonner";
import { ReactQueryClientProvider } from "@evolt/components/common/queryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  relative`}
      >
        <div className="w-[393px] h-[393px] bg-[#555CE4] rounded-full absolute top-[122.66px] left-1/2 -translate-x-1/2 blur-[1000px] z-[-1]"></div>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryClientProvider>
            <div className="relative z-10">{children}</div>

            <Toaster />
          </ReactQueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
